#!/bin/bash -x

# In Cygwin, remote smbfs shares are mounted using the 'mount' application

cd `dirname $0`/..

rm -rf bin
./configure --disable-fault-handling --without-pam --without-ad-dc --disable-python --without-gettext --without-cluster-support -v || exit 1
make -d -w --no-silent bin/smbclient || exit 1
make -d -w --no-silent bin/testparm || exit 1

